version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: champ-personal-homepage
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
